version: '3'
services:
  jazapi:
    build: ./jaz-api
    ports:
      - "11111:11111"
    restart: on-failure:5
    depends_on:
      - traindb
  jazclient:
    build: ./jaz-client
    ports:
      - "22222:22222"
    depends_on:
      - jazapi
  traindb:
    build: ./db
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_DATABASE: traindb
      MYSQL_USER: salesman
      MYSQL_PASSWORD: pwd